close all
clear all

Model = '001';
char_dt = '1m6';
Method = 'PenalizationSIRK2';
% Method = 'BackwardEuler';



load( [ 'Relaxation_Analytic_dt_' char_dt '_' Model '.mat' ] );

h = figure;

loglog...
  ( Time_A, Density_A(:,1) , '-k',...
    Time_A, Density_A(:,10), '-r',...
    Time_A, Density_A(:,20), '-g',...
    Time_A, Density_A(:,25), '-b',...
    Time_A, Density_A(:,30), '-m',...
    'linewidth', 2 )
% axis( [ 1.0d-9 1.0d-4 1.0d-4 1.0d+1 ] )
% axis( [ 1.0d-9 1.0d-4 1.0d-12 1.0d+1 ] )

hold on

load( ['SemiImplicit_' Method '_dt_' char_dt '_theta_0_' Model '.mat' ]);

loglog...
  ( Time, Density(:,1) , 'ok',...
    Time, Density(:,10), 'or',...
    Time, Density(:,20), 'og',...
    Time, Density(:,25), 'ob',...
    Time, Density(:,30), 'om',...
    'linewidth', 1 )

load( ['SemiImplicit_' Method '_dt_' char_dt '_theta_0_' Model '_SFHo.mat' ]);

loglog...
  ( Time, Density(:,1) , ':k',...
    Time, Density(:,10), ':r',...
    Time, Density(:,20), ':g',...
    Time, Density(:,25), ':b',...
    Time, Density(:,30), ':m',...
    'linewidth', 3 )
title(['Model=' Model ' ' Method ' R_{interpolated}']);

saveas(h,sprintf('temp.png'));